# Botman Configuration

[[bots]]
name = "AAA"
role = "fighter"
skills = []

[[bots]]
name = "BBB"
role = "gatherer"
skills = ["mining", "woodcutting"]

[[bots]]
name = "CCC"
role = "support"
skills = ["fishing", "cooking", "alchemy"]

[[bots]]
name = "DDD"
role = "crafter"
skills = ["weaponcrafting", "gearcrafting", "jewelrycrafting", "woodcutting"]

[[bots]]
name = "EEE"
role = "gatherer"
skills = ["mining", "woodcutting"]
