[project]
name = "botman"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.11.10",
    "pykka>=4.4.0",
    "ruff>=0.13.3",
]
